#!/bin/bash
# Tairon Battery Monitor
# Alerts if battery is low

BATTERY_THRESHOLD=25
NOTIFICATION_FLAG="/run/user/${UID}/tairon_battery_notified"
BATTERY_LEVEL="$(tairon-battery-remaining)"
BATTERY_STATE="$(upower -i "$(upower -e | grep 'BAT')" | grep -E "state" | awk '{print $2}')"

send_notification() {
  notify-send -u critical "Battery Low" "Battery is at ${BATTERY_LEVEL}%" -i battery-caution -t 30000
}

if [[ -n "${BATTERY_LEVEL}" && "${BATTERY_LEVEL}" =~ ^[0-9]+$ ]]; then
  if [[ "${BATTERY_STATE}" == "discharging" && "${BATTERY_LEVEL}" -le "${BATTERY_THRESHOLD}" ]]; then
    if [[ ! -f "${NOTIFICATION_FLAG}" ]]; then
      send_notification
      touch "${NOTIFICATION_FLAG}"
    fi
  else
    rm -f "${NOTIFICATION_FLAG}"
  fi
fi
