#!/bin/bash

fzf_args=(
  --multi
  --preview 'brew list {1}'
  --preview-label='alt-p: toggle description, alt-j/k: scroll, tab: multi-select'
  --preview-label-pos='bottom'
  --preview-window 'down:65%:wrap'
  --bind 'alt-p:toggle-preview'
  --bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up'
  --bind 'alt-k:preview-up,alt-j:preview-down'
  --color 'pointer:red,marker:red'
)

pkg_names=$(brew list | fzf "${fzf_args[@]}")

if [[ -n "${pkg_names}" ]]; then
  # Convert newline-separated selections to space-separated for yay
  echo "${pkg_names}" | tr '\n' ' ' | xargs brew remove
  echo
  gum spin --spinner "globe" --title "Done! Press any key to close..." -- bash -c 'read -n 1 -s'
fi
