#!/bin/bash

LOGO_FILE="${HOME}/.local/share/tarion/logo.txt"
SYSTEM_LOGO="/usr/share/tarion/logo.txt"

clear
echo -e "\033[32m"
if [[ -f "${LOGO_FILE}" ]]; then
  cat "${LOGO_FILE}"
elif [[ -f "${SYSTEM_LOGO}" ]]; then
  cat "${SYSTEM_LOGO}"
else
  echo "TARION"
fi
echo -e "\033[0m"
echo
