#!/bin/bash

# Launch a floating terminal with the Tarion logo presentation, then execute the command passed in, and finally end with the tarion-show-done presentation.
# Used by actions such as Update System.

cmd="$*"
exec setsid uwsm-app -- xdg-terminal-exec --app-id=org.tarion.terminal --title=Tarion -e bash -c "tarion-show-logo; ${cmd}; if [ \$? -ne 130 ]; then tarion-show-done; fi"
