set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    source /usr/lib/ujust/libformatting.sh
    echo "$(Urllink "https://docs.projectbluefin.io/administration#community-aliases-and-workarounds" "Click here to view the Universal Blue just documentation")"
    /usr/bin/ujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "just/00-default.just"
import "just/10-update.just"
import "just/15-luks.just"
import "just/20-clean.just"
import "just/30-distrobox.just"
import "just/40-nvidia.just"
import "just/50-akmods.just"
import "just/50-dev-tools.just"
import "just/50-tarion.just"
import? "just/60-custom.just"
