# Default Applications for Tarion
$terminal = ghostty
$fileManager = ghostty -e superfile
$browser = chromium-browser
$music = amberol
$messenger = thunderbird
$passwordManager = bitwarden
$menu = vicinae
$yazi = ghostty -e yazi
