# App-specific tweaks
source = hypr/apps/defaults.conf
source = hypr/apps/bitwarden.conf
source = hypr/apps/browser.conf
source = hypr/apps/pip.conf
source = hypr/apps/qemu.conf
source = hypr/apps/steam.conf
source = hypr/apps/system.conf
source = hypr/apps/terminals.conf
source = hypr/apps/webcam-overlay.conf
