exec-once = uwsm finalize

# Ensure DMS config directories and files exist before sourcing
exec-once = mkdir -p ~/.config/hypr/dms && touch ~/.config/hypr/dms/{colors,layout,outputs}.conf

# DMS shell
exec-once = dms run

exec-once = uwsm-app -- vicinae server --replace
exec-once = fcitx5
exec-once = uwsm-app -- valent --gapplication-service
